// <auto-generated />
using System;
using EventMicroservices.Services.OrderApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OrderApi.Migrations
{
    [DbContext(typeof(OrdersContext))]
    [Migration("20180829165638_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderApi.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("BuyerId");

                    b.Property<DateTime>("EventEndDate");

                    b.Property<int>("EventId");

                    b.Property<DateTime>("EventStartDate");

                    b.Property<string>("EventTitle");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("OrderStatus");

                    b.Property<decimal>("OrderTotal");

                    b.Property<string>("PaymentAuthCode");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("StripeToken");

                    b.Property<string>("UserName");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderApi.Models.OrderTicket", b =>
                {
                    b.Property<int>("TicketOrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId");

                    b.Property<string>("EventTitle");

                    b.Property<string>("ImageUrl");

                    b.Property<int>("OrderId");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int>("TicketTypeId");

                    b.Property<string>("TypeName");

                    b.HasKey("TicketOrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("OrderApi.Models.OrderTicket", b =>
                {
                    b.HasOne("OrderApi.Models.Order")
                        .WithMany("OrderTicket")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
